# Generated by Django 3.1.2 on 2020-10-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='availability',
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.CharField(blank=True, help_text='It is address image of category', max_length=255),
        ),
        migrations.AlterField(
            model_name='good',
            name='id_manufacturer',
            field=models.ForeignKey(help_text='It is foreign key of manufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer'),
        ),
        migrations.AlterField(
            model_name='good',
            name='sale',
            field=models.IntegerField(blank=True, help_text='Enter count of sale'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter email of user', max_length=254),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.CharField(blank=True, help_text='It is address image of manufacturer', max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.CharField(blank=True, help_text='It is address of website', max_length=128),
        ),
    ]
