# Generated by Django 3.1.2 on 2020-10-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of category', max_length=45)),
                ('description', models.TextField(help_text='Enter description of category')),
                ('availability', models.BooleanField(help_text='Is this kind of category exist?')),
                ('picture', models.CharField(help_text='It is address image of category', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of good', max_length=45)),
                ('description', models.TextField(help_text='Enter description of good')),
                ('availability', models.BooleanField(help_text='Is this kind of good exist?')),
                ('price', models.IntegerField(help_text='Enter price of good')),
                ('count', models.IntegerField(help_text='Enter count of good')),
                ('sale', models.IntegerField(blank=True, help_text='Enter count of sale', max_length=100)),
                ('picture', models.CharField(help_text='It is address image of good', max_length=255)),
                ('id_category', models.ForeignKey(help_text='It is foreign key of category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of manufacturer', max_length=45)),
                ('description', models.TextField(help_text='Enter description of manufacturer')),
                ('email', models.EmailField(help_text='Enter email of user', max_length=254)),
                ('logo', models.CharField(help_text='It is address image of manufacturer', max_length=255)),
                ('website', models.CharField(help_text='It is address of website', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of user', max_length=45)),
                ('last_name', models.CharField(help_text='Enter last name of user', max_length=45)),
                ('patronymic', models.CharField(help_text='Enter patronymic of user', max_length=45)),
                ('age', models.IntegerField(help_text='Enter age of user')),
                ('email', models.EmailField(help_text='Enter email of user', max_length=254)),
                ('phone_number', models.IntegerField(help_text='Enter phone number of user')),
                ('address', models.CharField(help_text='Enter addres of user', max_length=225)),
                ('login', models.CharField(help_text='Enter login of user', max_length=45)),
                ('password', models.CharField(help_text='Enter password of user', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datatime', models.DateTimeField()),
                ('delivery_datatime', models.DateTimeField()),
                ('status', models.CharField(help_text='It is status of our order', max_length=45)),
                ('good_id', models.ForeignKey(help_text='It is foreign key of good', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.good')),
                ('user_id', models.ForeignKey(help_text='It is foreign key of user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.user')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='id_manufacturer',
            field=models.ForeignKey(help_text='ForeignKey', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer'),
        ),
    ]
