# Generated by Django 3.1.2 on 2020-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201013_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='picture',
            field=models.CharField(blank=True, help_text='It is address image of good', max_length=255),
        ),
    ]
