# Generated by Django 3.1.2 on 2020-10-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201014_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sale',
        ),
    ]
